### ISSUE TITLE
Enhancement: Example Mod folder

### ISSUE THREAD

**Issue by DxrkPxwer** [CodenameCrew/CodenameEngine#256]
# I recently downloaded Codename and want to add stuff into it.

But i can't understand the functionality. Like, I'm trying to add a character into it, but i can't, because idk how to put it in.
And there's barely **ANY** tutorial on How to do this.

So, for people like me who has zero knowledge about the engine, it would be nice to add an **Example mod folder**.
That way, people can Has less problems like mine.

Edit: what if they added, like, an modchart editor?

**Comment by NexIsDumb** [comment]
oh we're actually sorry for that
the whole engine is still a big WIP so as for now there's no full wiki
although for now you can join the discord and ask in the help-modding channel if you wish to be helped by the community or even us main devs

**Comment by DxrkPxwer** [comment]
> oh we're actually sorry for that the whole engine is still a big WIP so for now there's no full wiki although for now you can join the discord and ask in the help-modding channel if you wish to be helped by the community or even us main devs

It's ok.

**Comment by DxrkPxwer** [comment]
like, i'm sure that other had something similar

**Comment by NexIsDumb** [comment]
yeah, we actually have plans for a better wiki or something similar so expect it in the future to come

**Comment by WizardMantis441** [comment]
the example you may be looking for is actually the assets folder!!! it's built exactly like a mods folder so you can copy the format of that

**Comment by CharlesCatYT** [comment]
or... just use **[this](https://github.com/Ve3h/Lazy-Mod-Folder-Template-for-Codename)** if you're feeling lazy lol

also, a modchart editor? uhhhhhhhh- eh. definitely won't happen. _ʸᵉᵗ·_

**Comment by ItsLJcool** [comment]
Very late on this but I made this [Codename Engine Template](https://github.com/ItsLJcool/Codename-Template-Generator) Generator (Windows only) and it has most folders you would need for CNE, and a link to the wiki in the readme (might be outdated rip)

[Wiki Link](https://codename-engine.com/)

**Comment by KadePleaseHelpMe** [comment]
please close this

**Comment by Treizvychar** [comment]
Hello, I wanted to make a mod for the mobile version. Is this possible Will it be done?
