### ISSUE TITLE
Enhancement: W And S Keys For Chart Editor

### ISSUE THREAD

**Issue by BoomLingReady** [CodenameCrew/CodenameEngine#391]
i use psych engine a Lot, and i use w and s to move my chart editor up and down, so can this be a feature? Scrolling is only for moving in the chart editor and.. its fine but w and s is the **goat**.
### -redready 2024

**Comment by KadePleaseHelpMe** [comment]
mods can we close this now that it's implemented

**Comment by NexIsDumb** [comment]
oh right
