### ISSUE TITLE
Bug Report: my game is ALWAYS black screen (i installed actions and it is my first time joining)

### ISSUE THREAD

**Issue by Eullim** [CodenameCrew/CodenameEngine#471]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[ X ] Windows
[ ] Linux
[ ] Mac

### Explain your issue

![image](https://github.com/user-attachments/assets/31fa2e4d-fe2b-4539-87df-2b56039fd344)

It's just a black screen! I tried re-opening the game, and it is still black screen!
##### Please check first if your issue haven't already been reported yet.
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)

**Comment by NeeEoo** [comment]
open cmd and run it
