### ISSUE TITLE
Bug Report: Error on Android

### ISSUE THREAD

**Issue by megalives717** [CodenameCrew/CodenameEngine#495]
![Screenshot_20241214-095017](https://github.com/user-attachments/assets/dd23e99e-e771-4149-bf02-8466dd1cb4fb)
[2024-12-14-09'53'51.txt](https://github.com/user-attachments/files/18134779/2024-12-14-09.53.51.txt)

**Comment by FuroYT** [comment]
Not related to us, report to their repo now ours

**Comment by moxie-coder** [comment]
> Not related to us, report to their repo now ours

exactly, also close this issue please since you’re an member

**Comment by megalives717** [comment]
please help

**Comment by NexIsDumb** [comment]
> please help
sorry but as for now mobile support is still an unofficial thing, unrelated to this repository and still in early tests
