### ISSUE TITLE
Enhancement: Editor on Mobile

### ISSUE THREAD

**Issue by megalives717** [CodenameCrew/CodenameEngine#498]
![Screenshot_20241215-165019](https://github.com/user-attachments/assets/102d7ed2-7af8-422a-b8d3-0f9ad1e7691f)
![Screenshot_20241215-165036](https://github.com/user-attachments/assets/9c111597-f075-4020-915e-da4e0192df47)
Why I Can't Use Editor on Mobile?

**Comment by NeeEoo** [comment]
Wrong repo

**Comment by megalives717** [comment]
I Don't Have to Connect Mouse and Keyboard Why?

**Comment by PetscopF** [comment]
> I Don't Have to Connect Mouse and Keyboard Why?

The chart editor is not designed for touchscreens. As a result, you **will** need to connect the specified peripherals, one example being through Bluetooth. Also, this is not the correct repository. **Post this in the actual Codename Engine mobile repository**: so far, mobile is only unofficial, so you need to post there.
