### ISSUE TITLE
Bug Report: Chart does not load

### ISSUE THREAD

**Issue by PeteyTheCat9** [CodenameCrew/CodenameEngine#511]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[x] Windows
[ ] Linux
[ ] Mac

### Explain your issue
I was making a chart for my mod, but after saving -- it just dissapears. No characters, no notes, no anything.
**It's being loaded from the folder the Chart Editor made, no modifications to it.**
It was also made late at night so i am NOT spending another half an hour to compile a different engine and rechart the whole thing. Can you help me?

![image](https://github.com/user-attachments/assets/907362fc-3ec9-468c-a329-b29cc508beb5)

[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)

**Comment by NeeEoo** [comment]
Send the chart

**Comment by PeteyTheCat9** [comment]
[chart.zip](https://github.com/user-attachments/files/18255082/chart.zip)

**Comment by MasterGamaDev** [comment]
this happens to me when i tried to use a chart of psych engine 1.0

**Comment by NexIsDumb** [comment]
erm
it work for me
![image](https://github.com/user-attachments/assets/3e49b9fc-cb80-4f18-aa07-8d7a491cf615)

**Comment by NexIsDumb** [comment]
can you try updating the engine to latest version?

**Comment by PeteyTheCat9** [comment]
I have the newest version of the engine, can you send me the build? (With the chart inside?)

**Comment by NexIsDumb** [comment]
> I have the newest version of the engine, can you send me the build? (With the chart inside?)

its literally just newest but all I did was just pasting the chart folder inside the test song

**Comment by PeteyTheCat9** [comment]
Oh okay, thanks for helping me. I'm using the engine for the first time, just some beginner errors, and again -- thank you very much for helping me.

**Comment by NexIsDumb** [comment]
np!
works fine now?

**Comment by PeteyTheCat9** [comment]
Gotta check, just got home.

**Comment by NexIsDumb** [comment]
alrighty

**Comment by PeteyTheCat9** [comment]
All works, how do you make a week to get the song on freeplay only?

**Comment by NexIsDumb** [comment]
kind of hard to explain here, just look at the weeks inside of assets/data/weeks
theres a list file and then the actual weeks folder too
also here on codename you can just create a mod with one song only without changing the weeks and its gonna display that song only in freeplay anyways

**Comment by PeteyTheCat9** [comment]
Thanks, if i had questions -- where should i ask?

**Comment by NeeEoo** [comment]
Check out our website for the wiki https://codename-engine.com/

and theres a link to the discord on the main page

**Comment by PeteyTheCat9** [comment]
Thanks, i'm using the engine for the first time. I guarantee i will have questions already 🤣. Again, thanks for helping me out.

**Comment by NexIsDumb** [comment]
> Thanks, i'm using the engine for the first time. I guarantee i will have questions already 🤣. Again, thanks for helping me out.

np!
